# Generated by Django 6.0.4 on 2026-04-11 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_start', models.TimeField(default='07:00')),
                ('access_end', models.TimeField(default='18:00')),
                ('late_threshold_minutes', models.IntegerField(default=15)),
                ('block_unpaid_fees', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Règles d'accès",
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_admin', models.EmailField(default='admin@etsia.cd', max_length=254)),
                ('notify_access_denied', models.BooleanField(default=True)),
                ('notify_expired_card', models.BooleanField(default=True)),
                ('notify_disabled_card', models.BooleanField(default=True)),
                ('notify_unpaid_fees', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paramètres Notifications',
            },
        ),
        migrations.CreateModel(
            name='RFIDSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_length', models.IntegerField(default=8)),
                ('max_cards_per_student', models.IntegerField(default=1)),
                ('card_validity_days', models.IntegerField(default=365)),
                ('card_auto_disable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paramètres RFID',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('permissions', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Université ETSIA', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Information Université',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
