# Generated by Django 6.0.4 on 2026-06-26

import uuid
from django.db import migrations, models


def populate_card_uuid(apps, schema_editor):
    Card = apps.get_model('core', 'Card')
    for card in Card.objects.filter(card_uuid__isnull=True):
        card.card_uuid = uuid.uuid4()
        card.save(update_fields=['card_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(populate_card_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='card',
            name='card_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
