# Generated by Django 6.0.4 on 2026-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_academicyear_department_faculty_card_assigned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module', 'label'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permission_refs',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.permission'),
        ),
    ]
