# Generated by Django 6.0.4 on 2026-07-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_professor_student_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='core.faculty'),
        ),
    ]
