# Generated by Django 6.0.4 on 2026-07-02 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_behavior_point_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionTuitionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_plans', to='core.academicyear')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_plans', to='core.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='TuitionInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.promotiontuitionplan')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentInstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='core.enrollment')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='core.tuitioninstallment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='promotiontuitionplan',
            constraint=models.UniqueConstraint(fields=('promotion', 'academic_year'), name='unique_tuition_plan_per_promotion_year'),
        ),
        migrations.AddConstraint(
            model_name='tuitioninstallment',
            constraint=models.UniqueConstraint(fields=('plan', 'installment_number'), name='unique_installment_number_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='tuitioninstallment',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__gte', 1), ('installment_number__lte', 4)), name='installment_number_between_1_and_4'),
        ),
        migrations.AddConstraint(
            model_name='studentinstallmentpayment',
            constraint=models.UniqueConstraint(fields=('enrollment', 'installment'), name='unique_payment_per_enrollment_installment'),
        ),
    ]
